# Configuration de Prometheus
prometheus:
  image:
    repository: prom/prometheus
    tag: "v2.52.0"
    pullPolicy: IfNotPresent
  scrapeInterval: 15s
  service:
    type: NodePort
    port: 9090
    nodePort: 30090
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Configuration de Grafana
grafana:
  image:
    repository: grafana/grafana
    tag: "10.2.2"
    pullPolicy: IfNotPresent
  adminPassword: "admin123"
  service:
    type: NodePort
    port: 80
    nodePort: 30030
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 150m
      memory: 128Mi

# Configuration Mailserver Exporter
mailserverExporter:
  image:
    repository: prom/node-exporter
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9100
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Configuration Roundcube Exporter
roundcubeExporter:
  image:
    repository: prom/node-exporter
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9101
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Configuration Node Exporter
nodeExporter:
  image:
    repository: prom/node-exporter
    tag: "v1.6.1"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9100

# Configuration Kube State Metrics
kubeStateMetrics:
  image:
    repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
    tag: "v2.9.2"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
