{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "monitoring.prometheus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    app: prometheus
  ports:
  - name: web
    port: {{ .Values.prometheus.service.port }}
    targetPort: web
    protocol: TCP
    {{- if and (eq .Values.prometheus.service.type "NodePort") .Values.prometheus.service.nodePort }}
    nodePort: {{ .Values.prometheus.service.nodePort }}
    {{- end }}
{{- end }}
