apiVersion: v1
kind: Service
metadata:
  name: mailserver-metrics
  namespace: email-stack
  labels:
    app: mailserver
    monitoring: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "25"
spec:
  clusterIP: None
  selector:
    app: mailserver
  ports:
  - name: smtp
    port: 25
    targetPort: 25
  - name: imap
    port: 143
    targetPort: 143
  - name: submission
    port: 587
    targetPort: 587
