name: CD Dry-Run Deployment

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      dry_run:
        description: 'Run in dry-run mode'
        required: true
        default: 'true'
        type: boolean

jobs:
  dry-run-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible playbook in dry-run mode
        run: ansible-playbook -i ansible/inventory.yml ansible/deploy-email-stack.yml --check
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_SSH_ARGS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
